### ISSUE TITLE
Civics won't open

### ISSUE THREAD

**Issue by angelodgreat** [chaorace/cqui#122] opened 2016-11-20 11:00 UTC
Civics won't open in the latest nightly

**Comment by jacks0nX** [comment] 2016-11-20 13:08
Can't confirm this, opens alright for me. Can you attach a savegame? Any conflicts perhaps?

**Comment by chaorace** [comment] 2016-11-22 02:28
@angelodgreat I'm going to close this issue since you've not responded in two days and we've been unable to reproduce your issue. If you're still having problems, please come to the Gitter IRC for help instead of creating an issue ticket. Thanks!

**Closed by chaorace** 2016-11-22 02:28 UTC
