### ISSUE TITLE
Big size of options window on 1366x768 resolution

### ISSUE THREAD

**Issue by atggta** [chaorace/cqui#355] opened 2017-02-27 13:10 UTC
Too big size of options window on 1366x768 resolution. I dont see buttons (OK, cancel, maybe something else)
![image](https://cloud.githubusercontent.com/assets/26062472/23362428/3e75499a-fd28-11e6-81ce-168b164b8b00.png)

**Comment by JHCD** [comment] 2017-02-27 15:05
There is no _OK_ or _save_ button, you have to press the pipe again.

**Comment by JHCD** [comment] 2017-02-27 15:09
@chaorace could be an enhancement to implement a _closingX_ or a "back"-button like here:
https://cloud.githubusercontent.com/assets/12496340/23296671/7505c98a-fa76-11e6-833e-76b861378b69.jpg

**Comment by atggta** [comment] 2017-02-27 15:35
@JHCD thanks. But pipe.. not very obvious. Before I tried to press Escape, but appeared Main menu. Current version is fine, Escape work correct.

**Comment by chaorace** [comment] 2017-03-01 00:24
Duplicate of #86

**Closed by chaorace** 2017-03-01 00:24 UTC
