### ISSUE TITLE
Resources don't show up correctly on Mac

### ISSUE THREAD

**Issue by cityshrimp** [chaorace/cqui#394] opened 2017-03-16 03:53 UTC
- Civ 1.0.3
- Mac OSX
- Full Screen w/ 1440x900 resolution

Example: 
<img width="176" alt="image" src="https://cloud.githubusercontent.com/assets/1673724/23981084/40e26da2-09c1-11e7-8d58-c2593607d98c.png">

**Comment by chaorace** [comment] 2017-03-16 05:13
Duplicate of closed issue #195. Please download the nightly from the OSX/Linux branch or the OSX/Linux workshop release linked from the main workshop page

**Closed by chaorace** 2017-03-16 05:13 UTC
