### ISSUE TITLE
Recommended Production?

### ISSUE THREAD

**Issue by thejase** [chaorace/cqui#121] opened 2016-11-20 05:33 UTC
Am I missing something, because I can't find the "recommended" aspect of the production screen.

![image](https://cloud.githubusercontent.com/assets/787276/20460676/cb685fea-ae9f-11e6-877e-748fd17432f1.png)

**Comment by chaorace** [comment] 2016-11-20 05:39
This is a duplicate of issue #51

**Closed by chaorace** 2016-11-20 05:39 UTC
