### ISSUE TITLE
Production button not working after save and load game

### ISSUE THREAD

**Issue by mwaxx29** [chaorace/cqui#104] opened 2016-11-15 20:52 UTC
Hi i recently tried this civ 6 mod. I like it however, whenever I saved and load it the production screen for the city won't open or pop-out. Attached image shows I've clicked on the change prod. button and the left hand city info. It made the game unplayable. 
![bug1](https://cloud.githubusercontent.com/assets/17952574/20323580/00743c14-ab43-11e6-9a81-411ad0d4e58f.jpg)

**Comment by chaorace** [comment] 2016-11-15 20:54
Are you on v0.6 or the latest nightly? Did this problem only start happening with this save or with every game?

**Comment by mwaxx29** [comment] 2016-11-15 20:57
It's version 0.6. I'm about to test it out on this new game hold on.

**Comment by chaorace** [comment] 2016-11-15 20:59
@mwaxx29 Actually, looking at your screenshot, you appear to be on the nightly. Could you update it to make sure you're on the latest one?

**Comment by mwaxx29** [comment] 2016-11-15 21:01
Ok, just updated it.

**Comment by mwaxx29** [comment] 2016-11-15 21:23
Yes production button works, however I lost the pop-up menu like in civ 5 overlay both production and city info screen. I can still use the production menu now though. It's a tough compromise but it works.

**Comment by chaorace** [comment] 2016-11-15 21:47
I've just realized you're using Yuri's Citypanel Mod. It's incompatible with CQUI because there's a custom version of it included in this mod. This is an issue caused by user error and I'll be closing this ticket now. If you do need any more help please feel free to keep using this thread!

**Closed by chaorace** 2016-11-15 21:47 UTC
