### ISSUE TITLE
Implement Production Queue mod

### ISSUE THREAD

**Issue by aesir112** [chaorace/cqui#74] opened 2016-11-11 04:55 UTC
The author seems open to the idea. Or at least make it compatible. http://forums.civfanatics.com/threads/production-queue.604711/ or https://github.com/kblease/ProductionQueue

**Comment by chaorace** [comment] 2016-11-11 05:33
Thanks for the heads up, but I'm already aware and this issue is a duplicate of #34

**Closed by chaorace** 2016-11-11 05:33 UTC
