### ISSUE TITLE
Fall Update: Clicking cog on city overhead name doesn't open production window

### ISSUE THREAD

**Issue by thejase** [chaorace/cqui#112] opened 2016-11-18 06:38 UTC
WISOTT.

I can still click on the cog in the lower-right HUD, but doing so on the city name does nothing.  Running v0.6 after Fall update.

**Comment by chaorace** [comment] 2016-11-18 06:52
I don't know what WISOTT is supposed to mean, sorry!

As for the cog thing, [I've had no such issue in the latest nightly](https://docs.google.com/uc?id=0BzRHuYM0ypGoU3dBcVU0ZTJrMkE), even on the fall patch. Could you check if this is being caused by some mod incompatibility?

Anyways, there's a dedicated issue for all fall update related problems, so I'm closing this. If I've misunderstood your issue and you're sure it's an issue with the mod, I encourage you to post over on issue #111. Thanks!

**Closed by chaorace** 2016-11-18 06:52 UTC

**Comment by Riskke** [comment] 2016-11-19 00:43
Hello, got the same problem. I removed Yuri's Divine panel (from the DLC folder) and never happened again (dunno if i could be running both mods anyway)

Hope i can help

**Comment by chaorace** [comment] 2016-11-19 00:54
Divine Yuri's Panel overwrites the file where the majority of the main control logic is for CQUI. Don't use both at once ever, it will break everything! There's a custom version of the custom city panel mod included in CQUI anyways, so there's no need to attempt using both mods anyways

**Comment by Riskke** [comment] 2016-11-19 00:56
I realized as the problem was around the UI, just trying to make the OP know. Keep the good work, amazing rework of the UI u are doing here

**Comment by thejase** [comment] 2016-11-19 01:49
Well whaddya know?  Removing Yuri's panel worked. So sorry for the distraction, and the vague acronym (What It Says On The Tin).  I forget that github work jargon gets lost in translation outside of the office.
