### ISSUE TITLE
Integrate Production Queue

### ISSUE THREAD

**Issue by gobec** [chaorace/cqui#77] opened 2016-11-11 10:37 UTC
Integrate  Production Queue mod
https://github.com/kblease/ProductionQueue

**Comment by RealAntithesis** [comment] 2016-11-11 12:07
This will be very nice :)

**Comment by jacks0nX** [comment] 2016-11-11 12:51
I'm already on it.
See #34.

**Comment by chaorace** [comment] 2016-11-11 19:38
This is a duplicate of #34

**Closed by chaorace** 2016-11-11 19:38 UTC
