### ISSUE TITLE
City screen/bubble gone after reload

### ISSUE THREAD

**Issue by caboose211** [chaorace/cqui#378] opened 2017-03-08 02:41 UTC
citys name bubble is gone after reload and the close buttons for city produciton no longer work. The only way I can close out of city produciton is to right click on the screen and then click on a unit. Only then does the city production list close.

**Comment by caboose211** [comment] 2017-03-08 04:30
only with the nq war mod

**Comment by chaorace** [comment] 2017-03-08 15:13
Duplicate of #264

**Closed by chaorace** 2017-03-08 15:13 UTC
Labels: duplicate
