### ISSUE TITLE
Production panel missing

### ISSUE THREAD

**Issue by datvigi** [chaorace/cqui#158] opened 2016-12-05 01:29 UTC
I installed the mod. All of the amazing features are there but the production panel in my city is missing. Is there a toggle I am not seeing. Fresh game after the install. Installed into my Mods folder and enabled as additional content.

**Comment by chaorace** [comment] 2016-12-05 01:43
I just loaded up the latest nightly and started a fresh save, I was unable to reproduce so I'll be closing this issue. I still want to help you with the issue at hand, so feel free to keep communicating with me in the comments until we sort this out, but in the future please use the Gitter IRC (which I notice you've already done)  instead of creating a new issue when troubleshooting something that's probably not a bug in the mod.

**Closed by chaorace** 2016-12-05 01:43 UTC

**Comment by datvigi** [comment] 2016-12-05 02:11
Will do in the future and I am really sorry for that. I am not familiar with how these projects work. I didn't do some more exploring, where I found the Gitter IRC, until after I made the issues post. I was wondering at that point if I hd made a big mistake and if the issues area was reserved for testers or something that is likely to be mod wide

**Comment by datvigi** [comment] 2016-12-05 02:12
I am wondering if I installed it correctly. I installed it, like most mods at this point, in the mods folder of this path C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods. Is that correct?

**Comment by chaorace** [comment] 2016-12-05 02:20
@datvigi 
No worries, I just wanna help you the best I can! Anyways, CQUI is developed as an install to the DLC folder, which is inside the actual Steam Civ 6 install. I've gotten reports that installing to the mods folder works just as well, but it's definitely something to consider trying if a mod conflict isn't the cause of the issue

**Comment by datvigi** [comment] 2016-12-05 02:23
Yeah, when I read the install instructions it didn't really make sense to me. But it I just move it to the Civ VI DLC Folder?

**Comment by chaorace** [comment] 2016-12-05 03:37
Yes, just extract the cqui folder to the DLC folder
