### ISSUE TITLE
[Request] Notification for pop growth

### ISSUE THREAD

**Issue by yavru** [chaorace/cqui#249] opened 2017-01-17 19:51 UTC
Is it possible to add a notification (can be in the gossip/status system instead of being a notification on the right as I believe those are hard-coded at the moment) to alert the player that a city has grown in population in the last turn? This was present in Civ IV, and it becomes really handy when the number of cities you control is large as it gets harder to remember in the later stages of the game.

**Comment by chaorace** [comment] 2017-01-18 09:39
Duplicate of #143

**Closed by chaorace** 2017-01-18 09:39 UTC
