### ISSUE TITLE
CQUI (and other) options not being remembered on reload

### ISSUE THREAD

**Issue by RealAntithesis** [chaorace/cqui#49] opened 2016-11-06 03:51 UTC
Is there a way to reapply the settings when the game is reloaded? If I select the 'Enhanced' binding options, popup visuals, hide the grid etc, then these aren't remembered when the game is reloaded. Which means selecting them all again.

**Comment by chaorace** [comment] 2016-11-06 04:04
This is a duplicate of issue #37

**Closed** 2016-11-06 04:04 UTC
Labels: duplicate
